In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv(r"IRIS.csv")
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
data.shape

(150, 5)

In [5]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
#Splitting dataset into training and testing dataset

x = data.drop(['species'],axis = 1)
y = data['species']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [7]:
#Applying PCA

from sklearn.decomposition import PCA
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [8]:
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.9195717  0.05707944 0.01850996 0.00483889]


In [9]:
#Use 1 principal component to train our algorithm

from sklearn.decomposition import PCA
pca = PCA(n_components = 1)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [10]:
#Build the model

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model = model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)

In [11]:
#Performance Evaluation

from sklearn.metrics import confusion_matrix,accuracy_score
print("Confusion Matrix:")
print(confusion_matrix(Y_test,Y_pred))
print("Accuracy Score:",round(accuracy_score(Y_test,Y_pred)*100,2),'%')

Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
Accuracy Score: 96.67 %
