In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv(r"diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
data.shape

(768, 9)

In [5]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
#Splitting the dataset into training and testing dataset

X = data.drop(['Outcome'],axis = 1)
Y = data['Outcome']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state = 20,test_size = 0.2)

In [7]:
#Build the model

from sklearn.svm import SVC
model1 = SVC(kernel = 'linear')
model2 = SVC(kernel = 'poly')
model3 = SVC(kernel = 'sigmoid')
model4 = SVC(kernel = 'rbf')
model1 = model1.fit(X_train,Y_train)
model2 = model2.fit(X_train,Y_train)
model3 = model3.fit(X_train,Y_train)
model4 = model4.fit(X_train,Y_train)
Y_pred_model1 = model1.predict(X_test)
print(Y_pred_model1)

[0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 1 0 1 1 0
 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0 1 0 1 0 0 0
 1 0 0 0 1 0]


In [8]:
Y_pred_model2 = model2.predict(X_test)
print(Y_pred_model2)

[0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0]


In [9]:
Y_pred_model3 = model3.predict(X_test)
print(Y_pred_model3)

[0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0
 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0
 0 0 0 0 0 0]


In [10]:
Y_pred_model4 = model4.predict(X_test)
print(Y_pred_model4)

[0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0]


In [11]:
#Confusion Matrix

from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(Y_test,Y_pred_model1)
print("Confusion Matrix for SVM-linear: ")
print(cm1)

Confusion Matrix for SVM-linear: 
[[88 13]
 [24 29]]


In [12]:
cm2 = confusion_matrix(Y_test,Y_pred_model2)
print("Confusion Matrix for SVM-polynomial: ")
print(cm2)

Confusion Matrix for SVM-polynomial: 
[[94  7]
 [30 23]]


In [13]:
cm3 = confusion_matrix(Y_test,Y_pred_model3)
print("Confusion Matrix for SVM-sigmoid: ")
print(cm3)

Confusion Matrix for SVM-sigmoid: 
[[77 24]
 [49  4]]


In [14]:
cm4 = confusion_matrix(Y_test,Y_pred_model4)
print("Confusion Matrix for SVM-rbf: ")
print(cm4)

Confusion Matrix for SVM-rbf: 
[[90 11]
 [30 23]]


In [15]:
#Accuracy Score

from sklearn.metrics import accuracy_score
print("Accuracy Score for SVM-linear: ",round(accuracy_score(Y_test,Y_pred_model1)*100,2),'%')
print("Accuracy Score for SVM-polynomial: ",round(accuracy_score(Y_test,Y_pred_model2)*100,2),'%')
print("Accuracy Score for SVM-sigmoid: ",round(accuracy_score(Y_test,Y_pred_model3)*100,2),'%')
print("Accuracy Score for SVM-rbf: ",round(accuracy_score(Y_test,Y_pred_model4)*100,2),'%')

Accuracy Score for SVM-linear:  75.97 %
Accuracy Score for SVM-polynomial:  75.97 %
Accuracy Score for SVM-sigmoid:  52.6 %
Accuracy Score for SVM-rbf:  73.38 %


In [16]:
#Classification Report

from sklearn.metrics import classification_report
print("Classification Report for SVM-linear: ")
print(classification_report(Y_test,Y_pred_model1))

Classification Report for SVM-linear: 
              precision    recall  f1-score   support

           0       0.79      0.87      0.83       101
           1       0.69      0.55      0.61        53

    accuracy                           0.76       154
   macro avg       0.74      0.71      0.72       154
weighted avg       0.75      0.76      0.75       154



In [17]:
print("Classification Report for SVM-polynomial: ")
print(classification_report(Y_test,Y_pred_model2))

Classification Report for SVM-polynomial: 
              precision    recall  f1-score   support

           0       0.76      0.93      0.84       101
           1       0.77      0.43      0.55        53

    accuracy                           0.76       154
   macro avg       0.76      0.68      0.69       154
weighted avg       0.76      0.76      0.74       154



In [18]:
print("Classification Report for SVM-sigmoid: ")
print(classification_report(Y_test,Y_pred_model3))

Classification Report for SVM-sigmoid: 
              precision    recall  f1-score   support

           0       0.61      0.76      0.68       101
           1       0.14      0.08      0.10        53

    accuracy                           0.53       154
   macro avg       0.38      0.42      0.39       154
weighted avg       0.45      0.53      0.48       154



In [19]:
print("Classification Report for SVM-rbf: ")
print(classification_report(Y_test,Y_pred_model4))

Classification Report for SVM-rbf: 
              precision    recall  f1-score   support

           0       0.75      0.89      0.81       101
           1       0.68      0.43      0.53        53

    accuracy                           0.73       154
   macro avg       0.71      0.66      0.67       154
weighted avg       0.72      0.73      0.72       154



In [20]:
print("Maxximum Accuracy Score: ")
maximum = max(round(accuracy_score(Y_test,Y_pred_model1)*100,2),round(accuracy_score(Y_test,Y_pred_model2)*100,2),round(accuracy_score(Y_test,Y_pred_model3)*100,2),round(accuracy_score(Y_test,Y_pred_model4)*100,2))
print(maximum,'%')

Maxximum Accuracy Score: 
75.97 %


In [21]:
new_df = pd.DataFrame({'Pregnancies':6,'Glucose':148,'BloodPressure':72,'SkinThickness':35,'Insulin':0,'BMI':33.6,'DiabetesPedigreeFunction':0.627,'Age':50},index = [0])
Y_pred1_model1 = model1.predict(new_df)
print(Y_pred1_model1)

[1]


In [22]:
Y_pred2_model2 = model2.predict(new_df)
print(Y_pred2_model2)

[1]


In [23]:
Y_pred3_model3 = model3.predict(new_df)
print(Y_pred3_model3)

[0]


In [24]:
Y_pred4_model4 = model4.predict(new_df)
print(Y_pred4_model4)

[1]
